Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -36,6 +36,17 @@ jobs:
         release_name: Release ${{ github.run_number }}
         draft: false
         prerelease: false
+
+    - name: Set APK Path
+      run: |
+        APK_DIR=$HOME/telegram-android/TMessagesProj/build/outputs/apk/afat/release
+        APK_PATH=$(ls $APK_DIR/*.apk | head -n 1)
+        if [ -z "$APK_PATH" ]; then
+          echo "Error: No APK found in $APK_DIR"
+          exit 1
+        fi
+        echo "Found APK at: $APK_PATH"
+        echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
     
     - name: Upload Play Store APK
       uses: actions/upload-release-asset@v1
@@ -43,6 +54,6 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: /home/source/TMessagesProj/build/outputs/apk/afat/release/app.apk
+        asset_path: $HOME/telegram-android/TMessagesProj/build/outputs/apk/afat/release/app.apk
         asset_name: telegram-playstore.apk
         asset_content_type: application/vnd.android.package-archive
